### ISSUE TITLE
[BUG] Not everyone have rank 

### ISSUE THREAD

**Issue by ddfigueiras** [KitsuneLab-Development/K4-System-MMRanks#1] opened 2024-03-27 02:29 UTC
**Describe the bug**
Only some people have rank. In my server all start at silver 1, 1000 points. But some people have no rank.

**To Reproduce**
Just fresh install with the config   "mode": 2,

https://prnt.sc/swQudYB5LLAq

**Comment by K4ryuu** [comment] 2024-03-27 09:40
This is not a bug. CSS has no protobufs implemented yet, that means the server cannot have a message to reveal all player rank. You see only your friends and so. Whenever CSS has this feature, it can be done. I close the issue.

**Closed as not planned by K4ryuu** 2024-03-27 09:40 UTC
Labels: bug

**Comment by ddfigueiras** [comment] 2024-03-29 13:58
But there are people that I'm not friend with that have it:
![image](https://github.com/K4ryuu/K4-System-MMRanks/assets/40365637/7349239a-878d-4d9d-9c72-4c603764d60a)
![image](https://github.com/K4ryuu/K4-System-MMRanks/assets/40365637/b598b0bb-cc71-42c7-a93c-84d3d4610790)

**Comment by K4ryuu** [comment] 2024-03-30 00:14
Its full random until we have no protobuffs x)
Thats what the "your friends or so" means.

**Comment by chycken** [comment] 2024-04-04 10:56
@K4ryuu does the cssharp's author (roffl) already know this 'issue'?

**Comment by K4ryuu** [comment] 2024-04-06 13:46
This is not an issue. It's just not implemented feature yet.
As the rofl said: ["protobuf is a bit painful"](https://discord.com/channels/1160907911501991946/1160925208203493468/1215526302992437319)

**Comment by chycken** [comment] 2024-04-06 14:03
> This is not an issue. It's just not implemented feature yet. As the rofl said: ["protobuf is a bit painful"](https://discord.com/channels/1160907911501991946/1160925208203493468/1215526302992437319)

Thanks, i think it will take a lot of time, until then we can use a metamod rank plugin for this (bc it working/showing all player's fake ranks in the scoreboard)

**Comment by K4ryuu** [comment] 2024-04-10 14:12
Fix for the players invisible ranks: https://github.com/K4ryuu/K4-System-MMRanks/issues/2#issuecomment-2047576708
